# Google Cloud Build設定ファイル
steps:
  # バックエンドのビルドとデプロイ
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/posting-app-backend:$BUILD_ID'
      - '-f'
      - 'backend/Dockerfile.cloudrun'
      - './backend'
    id: 'build-backend'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/posting-app-backend:$BUILD_ID'
    id: 'push-backend'
    waitFor: ['build-backend']

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'posting-app-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/posting-app-backend:$BUILD_ID'
      - '--platform'
      - 'managed'
      - '--region'
      - '$_REGION'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'PORT=8080,GO_ENV=production'
      - '--set-secrets'
      - 'DB_HOST=DB_HOST:latest,DB_USER=DB_USER:latest,DB_PASSWORD=DB_PASSWORD:latest,JWT_SECRET=JWT_SECRET:latest,STRIPE_SECRET_KEY=STRIPE_SECRET_KEY:latest'
    id: 'deploy-backend'
    waitFor: ['push-backend']

  # フロントエンドのビルドとデプロイ
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/posting-app-frontend:$BUILD_ID'
      - '-f'
      - 'front/Dockerfile.cloudrun'
      - '--build-arg'
      - 'REACT_APP_API_URL=https://posting-app-backend-${_RANDOM_SUFFIX}-uc.a.run.app/api'
      - './front'
    id: 'build-frontend'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/posting-app-frontend:$BUILD_ID'
    id: 'push-frontend'
    waitFor: ['build-frontend']

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'posting-app-frontend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/posting-app-frontend:$BUILD_ID'
      - '--platform'
      - 'managed'
      - '--region'
      - '$_REGION'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '5'
    id: 'deploy-frontend'
    waitFor: ['push-frontend']

# 置換変数
substitutions:
  _REGION: 'us-central1'
  _RANDOM_SUFFIX: 'unique'

# タイムアウト設定
timeout: '1200s'

# ログ設定
options:
  logging: CLOUD_LOGGING_ONLY